* Notes for HIS 45Y1-Y
*** <2010-09-16 Thu> Class notes Intro
**** What's this class about?
experiment in digital production/community engagement.  Why we do digital media, why we make history, lifelong learning, collaboration, ivory towers.  
**** Why we should write history:  what is its social function?  community, etc.
**** Collaborative Research, the web opens up possibilities, etc.  knowledge production as different from consumption, data mining means its poss to filter & so forth, goal of lib education is lifelong learning but also lifelong making of knowledge
**** Names
***** David  history specialist, renaissance, 
***** Vanessa, history/ir; back to school; no real interest ;
***** Ken, non-degre student -- mostly interested in social history; [DROP]
***** Mahavish, 4th yr specialist; ea studies;
***** Scott, specialist in history/religion major; ww2, holocaust; 
***** Istander?  4th yr his/poli sci; am studies/cold war history
***** Kira, 4th yr spcialist, russin history;
***** Mahmoud, Poli Sci/Hodern History; recent political history; passopenP --
***** Natasha, Specialist, south asian/diaspora studies HistoryPIN,
***** Jason, 5th yr his/can studies major; focus on canadia history;
***** Stefano:  Wikibooks, 
*** <2010-09-30 Thu> Class Notes Public sphere
**** Mark Poster, [[http://www.hnet.uci.edu/mposter/writings/democ.html][Cyberdemocracy]]

The Stakes of the Question

... The question of potentials for new forms of social space that might empower individuals in new ways are foreclosed in favor of preserving existing relations of force as they are viewed by the most powerful institution in the history of the world, the government of the United States.

The issue of commodification also affords a narrow focus... While there is no doubt that the Internet folds into existing social functions and extends them in new ways, translating the act of shopping, for example, into an electronic form, what are far more cogent as possible long term political effects of the Internet are the ways in which it institutes new social functions, ones that do not fit easily within those of characteristicallymodern organizations. The problem is that these new functions can only become intelligible if a framework is adopted that does not limit the discussion from the outset to modern patterns of interpretation... To ask then about the relation of the Internet to democracy is to challenge or to risk challenging our existing theoretical approaches and concepts as they concern these questions.
*Poster calls attention to 

If one places in brackets political theories that address modern governmental institutions in order to open the path to an assessment of the "postmodern" possibilities suggested by the Internet, two difficulties immediately emerge: (1) there is no adequate "postmodern" theory of politics and (2) the issue of democracy, the dominant political norm and ideal, is itself a "modern" category associated with the project of the Enlightenment. Let me address these issues in turn.



Recently theorists such as Philippe LacoueLabarthe and Jean-Luc Nancy [. Philippe Lacoue-Labarthe, Heidegger, Art and Politics, trans. Chris Turner (New York: Blackwell, 1990) and Jean-Luc Nancy, The Inoperative Community, trans. Peter Conor et al (Minneapolis: University of Minnesota Press, 1991).] have pointed to the limitations of a "left/right" spectrum of ideologies for addressing contemporary political issues. Deriving from seating arrangements of legislators during the French Revolution of 1789, the modern ideological spectrum inscribes a grand narrative of liberation which contains several problematic aspects. First it installs a linear, evolutionary and progressive history that occludes the differential temporalities of nonWestern groups and women, and imposes a totalizing, strong interpretation of the past that erases from view gaps, discontinuities, improbabilities, contingencies, in short apanoply of phenomena that might better be approached from a nonlinear perspective. Second the Enlightenment narrative establishes a process of liberation at the heart of history which requires at its base a presocial, foundational, individual identity. The individual is posited as outside of and prior to history, only later becoming ensnared in externally imposed chains. Politics for this modern perspective is then the arduous extraction of an autonomous agent from the contingent obstacles imposed by the past. In its rush to ontologize freedom, the modern view of the subject hides the process of its historical construction. A postmodern orientation would have to allow for the constitution of identity within the social and within language, displacing the question of freedom from a presupposition of and a conclusion to theory to become instead a pretheoretical or nonfoundational discursive preference. Postmodern theorists have discovered that modern theory's insistence on the freedom of the subject, its compulsive, repetitive inscription into discourse of the sign of the resisting agent, functions to restrict the shape of identity to its modern form, an ideological and legitimizing gesture of its own position rather than a step towards emancipation. If a postmodern perspective is to avoid the limits of modern theory, it is proscribed from ontologizing any form of the subject. The postmodern position is limited to an insistence on the constructedness of identity. In the effort to avoid the pitfalls of modern political theory, then, postmodern theory sharply restricts the scope of its ability to define a new political direction. This theoretical asceticism is a contemporary condition of discourse imposing an unusual discipline and requiring a considerable suspension of disbelief on the part of the audience. To skeptics it can only be said that the alternatives, those of "modern" positions, are even lessdesirable.

But there are further difficulties in establishing a position from which to recognize and analyze the cultural aspect of the Internet. For postmodern theory still invokes the modern term democracy, even when this is modified by the adjective "radical" as in the work of Ernesto Laclau. [. Ernesto Laclau, New Reflections on the Revolution of Our Time (New York: Verso, 1990).] One may characterize postmodern or postMarxist democracy in Laclau's terms as one that opens new positions of speech, empowering previously excluded groups and enabling new aspects of social life to become part of the political process. While the Internet is often accused of elitism (a mere thirty million users), there does exist a growing and vibrant grass-roots participation in it organized in part by local public libraries. [. See Jean Armour Polly and Steve Cisler, "Community Networks on the Internet," Library Journal (June 15, 1994) pp. 22-23.] But are not these initiatives, the modern skeptic may persist, simply extensions of existing political institutions rather than being "post," rather than being a break of some kind? In response I can assert only that the "postmodern" position need not be taken as a metaphysical assertion of a new age; that theorists are trapped within existing frameworks as much as they may be critical of them and wish not to be; that in the absence of a coherent alternative political program the best one can do is to examine phenomena such as the Internet in relation to new forms of the old democracy, while holding open the possibility that what might emerge might be something other than democracy in any shape that we may conceive it given our embeddedness in the present. Democracy, the rule by all, is surely preferable to its historic alternatives. And the term may yet contain critical potentials since existing forms of democracy surely do not fulfill the promise of freedom and equality. The colonization of the term by existing institutions encourages one to look elsewhere for the means to name the new patterns offorce relations emerging in certain parts of the Internet.

Decentralized Technology

My plea for indulgence with the limitations of the postmodern position on politics quickly gains credibility when the old question of technological determinism is posed in relation to the Internet. For when the question of technology is posed we may see immediately how the Internet disrupts the basic assumptions of the older positions. The Internet is above all a decentralized communication system. Like the telephone network, anyone hooked up to the Internet may initiate a call, send a message that he or she has composed, and may do so in the manner of the broadcast system, that is to say, may send a message to many receivers, and do this either in "real time" or as stored data or both. The Internet is also decentralized at a basic level of organization since, as a network of networks, new networks may be added so long as they conform to certain communications protocols. As an historian I find it fascinating that this unique structure should emerge from a confluence of cultural communities which appear to have so little in common: the Cold War Defense Department which sought to insure survival against nuclear attack by promoting decentralization, the countercultural ethos of computer programming engineers which had a deep distaste for any form of censorship or active restraint of communications and the world university research which I am at a loss to characterize. Added to this is a technological substratum of digital electronics which unifies all symbolic forms in a single system of codes, rendering transmissioninstantaneous and duplication effortless. If the technological structure of the Internet institutes costless reproduction, instantaneous dissemination and radical decentralization, what might be its effects upon the society, the culture and the political institutions?

There can be only one answer to this question and that is that it is the wrong question. Technologically determined effects derive from a broad set of assumptions in which what is technological is a configuration of materials that effect other materials and the relation between the technology and human beings is external, that is, where human beings are understood to manipulate the materials for ends that they impose upon the technology from a preconstituted position of subjectivity. But what the Internet technology imposes is a dematerialization of communication and in many of its aspects a transformation of the subject position of the individual who engages within it. The Internet resists the basic conditions for asking the question of the effects of technology. It installs a new regime of relations between humans and matter and between matter and nonmatter, reconfiguring the relation of technology to culture and thereby undermining the standpoint from within which, in the past, a discourse developed -- one which appeared to be natural -- about the effects of technology. The only way to define the technological effects of the Internet is to build the Internet, to set in place a series of relations which constitute an electronic geography. Put differently the Internet is more like a social space than a thing so that its effects are more like those of Germany than those of hammers. The effects of Germany upon the people within it is to make them Germans (at least for the most part); the effects of hammers is not to make people hammers,though Heideggerians and some others might disagree, but to force metal spikes into wood. As long as we understand the Internet as a hammer we will fail to discern the way it is like Germany. The problem is that modern perspectives tend to reduce the Internet to a hammer. In the grand narrative of modernity, the Internet is an efficient tool of communication, advancing the goals of its users who are understood as preconstituted instrumental identities.

The Internet, I suppose like Germany, is complex enough so that it may with some profit be viewed in part as a hammer. If I search the database functions of the Internet or if I send email purely as a substitute for paper mail, then its effects may reasonably be seen to be those on the order of the hammer. The database on the Internet may be more easily or cheaply accessed than its alternatives and the same may be said of email in relation to the Post Office or the FAX machine. But the aspects of the Internet that I would like to underscore are those which instantiate new forms of interaction and which pose the question of new kinds of relations of power between participants. The question that needs to be asked about the relation of the Internet to democracy is this: are there new kinds of relations occuring within it which suggest new forms of power configurations between communicating individuals? In other words, is there a new politics on the Internet? One way to approach this question is to make a detour from the issue of technology and raise again the question of a public sphere, gauging the extent to which Internet democracy may become intelligible in relation to it. To frame the issue of the political nature of the Internet in relation to the concept of the public sphere is particularly appropriate because of the spatial metaphor associated with the term. Instead of animmediate reference to the structure of an institution, which is often a formalist argument over procedures, or to the claims of a given social group, which assumes a certain figure of agency that I would like to keep in suspense, the notion of a public sphere suggests an arena of exchange, like the ancient Greek agora or the colonial New England town hall. If there is a public sphere on the Internet, who populates it and how? In particular one must ask what kinds of beings exchange information on this public sphere? Since there occurs no face-to-face interaction, only electronic flickers [. See N. Katherine Hayles, "Virtual Bodies and Flickering Signifiers," October 66 (Fall 1993) pp. 69-91.] on a screen, what kind of community can there be in this space? What kind of disembodied politics are inscribed so evanescently in cyberspace? Modernist curmudgeons may object vehemently against attributing to information flows on the Internet the dignified term "community." Are they correct and if so what sort of phenomenon is this cyberdemocracy?

The Internet as a Public Sphere ?

The issue of the public sphere is at the heart of any reconceptualization of democracy. Contemporary social relations seem to be devoid of a basic level of interactive practice which, in the past, was the matrix of democratizing politics: loci such as the agora, the New England town hall, the village Church, the coffee house, the tavern, the public square, a convenient barn, a union hall, a park, a factory lunchroom, and even a street corner. Many of these places remain but no longer serve as organizingcenters for political discussion and action. It appears that the media, especially television but also other forms of electronic communication isolate citizens from one another and sustitute themselves for older spaces of politics. An example from the Clinton heath-care reform campaign will suffice: the Clinton forces at one point (mid-July 1994) felt that Congress was less favorable to their proposal than the general population. To convince the Congress of the wisdom of health-care reform, the adminstration purchased television advertising which depicted ordinary citizens speaking in favor of the legislation. The ads were shown only in Washington D.C. because they were directed not at the general population of viewers but at congressmen and congresswomen alone. The executive branch deployed the media directly on the legislative branch. Such are politics in the era of the mode of information. In a context like this one may ask where is the public sphere, where is the place citizens interact to form opinions in relation to which public policy must be attuned? John Hartley makes the bold and convincing argument that the media are the public sphere: "Television, popular newspapers, magazines and photography, the popular media of the modern period, are the public domain, the place where and the means by which the public is created and has its being." [. For a study of the role of the media in the formation of a public sphere see John Hartley, The Politics of Pictures: The Creation of the Public in the Age of Popular Media (New York: Routledge, 1992) p.1. Hartley examines in particular the role of graphic images in newspapers.] The same claim is offered by Paul Virilio: "Avenues and public venues from now on are eclipsed by the screen, by electronic displays, in a preview of the `vision machines' just around the corner." [. Paul Virilio, The Vision Machine, trans. Julie Rose (Bloomington: Indiana University Press, 1994) p. 64.] "Public" tends more and more to slide into "publicity" as "character" is replaced by "image." These changes must be examined without nostalgia and the retrospective glance of modernist politics and theory.

Sensing a collapse of the public sphere and therefore a crisis of democraticpolitics, J¸rgen Habermas published The Structural Transformation of the Public Sphere in 1962. [. J¸rgen Habermas, The Structural Transformation of the Public Sphere, trans. Thomas Burger (Cambridge: MIT Press, 1989).] In this highly influential work he traced the development of a democratic public sphere in the seventeenth and eighteenth centuries and charted its course to its decline in the twentieth century. In that work and arguably since then as well, Habermas' political intent was to further "the project of Enlightenment" by the reconstruction of a public sphere in which reason might prevail, not the instrumental reason of much modern practice but the critical reason that represents the best of the democratic tradition. Habermas defined the public sphere as a domain of uncoerced conversation oriented toward a pragmatic accord. His position came under attack by poststructuralists like Lyotard who questioned the emancipatory potentials of its model of consensus through rational debate. [. Jean-FranÁois Lyotard, The Postmodern Condition, trans. Brian Massumi et al (Minneapolis: University of Minnesota Press, 1984).] At issue was the poststructuralist critique of Habermas' Enlightenment ideal of the autonomous rational subject as a universal foundation for democracy. Before deploying the category of the public sphere to evaluate democracy on the Internet, I shall turn to recent developments in the debate over Habermas' position.

In the 1980s Lyotard's critique was expanded by feminists like Nancy Fraser who demonstrate the gender blindness in Habermas' position. [. Nancy Fraser, "Rethinking the Public Sphere," Social Text 25/26 (1990) pp. 56-80 and Unruly Practices (Minneapolis: University of Minnesota Press, 1989) especially Ch. 6 "What's Critical about Critical Theory? The Case of Habermas and Gender." For a critique of Habermas' historical analysis see Joan Landes, Women and the Public Sphere in the Age of the French Revolution (Ithaca: Cornell University Press, 1988). ] Even before the poststructuralists and feminists, Oskar Negt and Alexander Kluge began the critique of Habermas by articulating the notion of an oppositional public sphere, specifically that of the proletariat. What is important about their argument, as demonstrated so clearly by Miriam Hansen, is that Negt and Kluge shifted the terrain of the notion of the public sphere from an historico-transcendental idealization of the Enlightenment to a plurality and heterotopia of discourses. This crucial change in the notion of the public sphereassumes its full significance when it is seen in relation to liberal democracy. The great ideological fiction of liberalism is to reduce the public sphere to existing democratic institutions. Habermas' critique of liberalism counterposes a radical alternative to it but one that still universalizes and monopolizes the political. Negt and Kluge, in contrast, decentralize and mutliply the public sphere, opening a path of critique and possibly a new politics. [. Oskar Negt and Alexander Kluge, Public Sphere and Experience: Toward an Analysis of the Bourgeois and Proletarian Public Sphere, trans. Peter Labanyi et al (Minneapolis: University of Minnesota Press, 1993). The foreword by Miriam Hansen (pp.ix-xli) is essential and important in its own right.] The final step in the development of the concept of the public sphere came with Rita Felski's synthesis of Negt/Kluge with both feminist gender analysis and the poststructuralist critique of the autonomous subject. For Felski the concept of the public sphere must build on the "experience" of political protest (in the sense of Negt and Kluge), must acknowledge and amplify the mutliplicity of the subject (in the sense of poststructuralism) and must account for gender differences (in the sense of feminism). She writes:

Unlike the bourgeois public sphere, then, the feminist public sphere does not claim a representative universality but rather offers a critique of cultural values from the standpoint of women as a marginalized group within society. In this sense it constitues a partial or counterpublic sphere.... Yet insofar as it is a public sphere, its arguments are also directed outward, toward a dissemination of feminist ideas and values throughout society as a whole. [. Rita Felski, Beyond Feminist Aesthetics: Feminist Literature and Social Change (Cambridge: Harvard University Press, 1989) p. 167.]

Felski seriously revises the Habermasian notion of the public sphere, separating it from its patriarchal, bourgeois and logocentric attachments perhaps, but nonetheless stillinvoking the notion of a public sphere and more or less reducing politics to it. This becomes clear in the conclusion of her argument: "Some form of appeal to collective identity and solidarity is a necessary precondition for the emergence and effectiveness of an oppositional movement; feminist theorists who reject any notion of a unifying identity as a repressive fiction in favor of a stress on absolute difference fail to show how such diversity and fragmentation can be reconciled with goaloriented political struggles based upon common interests. An appeal to a shared experience of oppression provides the starting point from which women as a group can open upon the problematic of gender, at the same time as this notion of gendered community contains a strongly utopian dimension...." (pp.168-9) In the end Felski sees the public sphere as central to feminist politics. But then we must ask how this public sphere is to be distinguished from any political discussion? From the heights of Habermas' impossible (counter-factual) ideal of rational communication, the public sphere here multiplies, opens and extends to political discussion by all oppressed individuals.

The problem we face is that of defining the term "public." Liberal theory generally resorted to the ancient Greek distinction between the family or household and the polis, the former being "private" and the latter "public." When the term crossed boundaries from political to economic theory, with Ricardo and Marx, a complication set in: the term "political economy" combined the Greek sense of public and the Greek sense of private since economy refered for them to the governance of the (private) household. The older usage preserved a space for the public in the agora to be sure but referred to discussions about the general good, not market transactions. In the newer usage theeconomic realm is termed "political economy" but is considered "private." To make matters worse, common parlance nowadays has the term "private" designating speeches and actions that are isolated, unobserved by anyone and not recorded or monitored by any machine. [. See the discussion of privacy in relation to electronic surveillance in David Lyon, The Electronic Eye: The Rise of Surveillance Society (Minneapolis: University of Minnesota Press, 1994) pp. 14-17.] Privacy now becomes restricted to the space of the home, in a sense returning to the ancient Greek usage even though family structure has altered dramatically in the interum. In Fraser's argument, for example, the "public" sphere is the opposite of the "private" sphere in the sense that it is a locus of "talk," "...a space in which citizens deliberate about their common affairs..." and is essential to democracy. [. Nancy Fraser, "Rethinking the Public Sphere," p. 57.] There are serious problems then in using the term "public" in relation to a politics of emancipation.

This difficulty is amplified considerably once newer electronically mediated communications are taken into account, in particular the Internet. Now the question of "talk," of meeting face-to-face, of "public" discourse is confused and complicated by the electronic form of exchange of symbols. If "public" discourse exists as pixels on screens generated at remote locations by individuals one has never and probably will never meet, as it is in the case of the Internet with its "virtual communities," "electronic cafÈs," bulletin boards, e-mail, computer conferencing and even video conferencing, then how is it to be distinguished from "private" letters, printface and so forth. The age of the public sphere as face-to-face talk is clearly over: the question of democracy must henceforth take into account new forms of electronically mediated discourse. What are the conditions of democratic speech in the mode of information? What kind of "subject" speaks or writes or communicates in these conditions? What is its relation to machines? What complexesof subjects, bodies and machines are required for democratic exchange and emancipatory action? For Habermas, the public sphere is a homogeneous space of embodied subjects in symmetrical relations, pursuing consensus through the critique of arguments and the presentation of validity claims. This model, I contend, is systematically denied in the arenas of electronic politics. We are advised then to abandon Habermas' concept of the public sphere in assessing the Internet as a political domain.

Against my contention, Judith Perrolle turns to a Habermasian perspective to look at conversations on bulletin boards and finds that the conditions of the ideal speech situation do not apply. She contends that these conversations are "distorted" by a level of machine control: here validity "...claims of meaningfulness, truth, sincerity and appropriateness... appear to be physical or logical characteristics of the machine rather than an outcome of human negotiation." [. Judith Perrolle, "Conversations and Trust in Computer Interfaces," in Charles Dunlop and Rob Kling, eds., Computerization and Controversy (New York: Academic Press, 1991) p. 351.] The basic conditions for speech are configured in the program of the virtual community and remain outside the arena of discussion. She continues: "Most computer interfaces are either not designed to allow the user to question data validity, or else designed so that data may be changed by anyone with a moderate level of technical skill." (p. 354) While this argument cannot be refuted from within the framework of Habermas' theory of communicative action, the question remains if these criteria are able to capture the specific qualities of the electronic forms of interaction.

Now that the thick culture of information machines provides the interface for much if not most discourse on political issues, the fiction of the democratic community of fullhuman presence serves only to obscure critical reflection and divert the development of a political theory of this decidedly postmodern condition. For too long critical theory has insisted on a public sphere, bemoaning the fact of media "interference," the static of first radio's then of television's role in politics. But the fact is that political discourse has long been mediated by electronic machines: the issue now is that the machines enable new forms of decentralized dialogue and create new combinations of human-machine assemblages, new individual and collective "voices," "specters," "interactivities" which are the new buidling blocks of political formations and groupings. As Paul Virilio writes, "What remains of the notion of things `public' when public images (in real time) are more important than public space?" [. Paul Virilio, "The Third Interval: A Critical Transition," in Verena Conley, ed. , Rethinking Technologies (Minneapolis: University of Minnesota Press, 1993) p. 9.] If the technological basis of the media has habitually been viewed as a threat to democracy, how can theory account for the turn toward a construction of technology (the Internet) which appears to promote a decentralization of discourse if not democracy itself and appears to threaten the state (unmonitorable conversations), mock at private property (the infinite reproducibility of information) and flaunt moral propriety (the dissemination of images of unclothed people often in awkward positions)?

A Postmodern Technology ?

Many areas of the Internet extend pre-existing identities and institutions. Usenet newsgroups elicit obnoxious pranks from teenage boys; databases enable researchers and corporations to retrieve information at lower costs; electronic mail affords speedy,reliable communication of messages; the digitization of images allows a wider distribution of erotic materials, and so it goes. The Internet then is modern in the sense of continuing the tradition of tools as efficient means and in the sense that prevailing modern cultures transfer their characteristics to the new domain. These issues remain to be studied in detail and from a variety of standpoints, but for the time being the above conclusion may be sustained. Other areas of the Internet are less easy to contain within modern points of view. The examination of these cyberspaces raises the issue of a new understanding of technology and finally leads to a reassessment of the political aspects of the Internet. I refer to the bulletin board services that have come to be known as "virtual communities," to the MOO phenomenon and to the synthesis of virtual reality technology with the Internet.

In these cases what is at stake is the direct solicitation to construct identities in the course of communication practices. Individual's invent themselves and do so repeatedly and differentially in the course of conversing or messaging electronically. Now there is surely nothing new in discursive practices that are so characterized: reading a novel, [. MarieLaure Ryan, "Immersion vs. Interactivity: Virtual Reality and Literary Theory," Postmodern Culture, 5:1 (September, 1994) presents a subtle, complex comparison of reading a novel and virtual reality. She does not deal directly with MOOs and Internet virtual communities.] speaking on CB radio, indeed watching a television advertisement, I contend, all in varying degrees and in different ways encourage the individual to shape an identity in the course of engaging in communication. The case of the limited areas of the Internet I listed above, however, goes considerably beyond, or at least is quite distinct from, the latter examples. The individual's performance of the communication requires linguistic acts of self-positioning that are less explicit in the cases of reading a novel or watching a television advertisement. On the Internet, individuals read and interpret communicationsto themselves and to others and also respond by shaping sentences and transmitting them. Novels and TV ads are interpreted by individuals who are interpellated by them but these readers and viewers are not addressed directly, only as a generalized audience and, of course, they respond in fully articulated linguistic acts. (I avoid framing the distinction I am making here in the binary active/passive because that couplet is so associated with the modern autonomous agent that it would appear that I am depicting the Internet as the realization of the modern dream universal, "active" speech. I refuse this resort because it rests upon the notion of identity as a fixed essence, presocial and prelinguistic, whereas I want to argue that Internet discourse constitutes the subject as the subject fashions him or herself. I want to locate subject constitution at a level which is outside the oppositions of freedom/determinism, activity/passivity.) On the Internet individuals construct their identities, doing so in relation to ongoing dialogues not as acts of pure consciousness. But such activity does not count as freedom in the liberal-Marxist sense because it does not refer back to a foundational subject. Yet it does connote a "democratization" of subject constitution because the acts of discourse are not limited to one-way address and not constrained by the gender and ethnic traces inscribed in face-to-face communications. The "magic" of the Internet is that it is a technology that puts cultural acts, symbolizations in all forms, in the hands of all participants; it radically decentralizes the positions of speech, publishing, filmmaking, radio and television broadcasting, in short the apparatuses of cultural production.

Gender and Virtual Communities

Let us examine the case of gender in Internet communication as a way to clarify what is at stake and to remove some likely confusions about what I am arguing. Studies have pointed out that the absence of gender cues in bulletin board discussion groups does not eliminate sexism or even the hierarchies of gender that pervade society generally. [. Lynn Cherny, "Gender Differences in Text-Based Virtual Reality," Proceedings of the Berkeley Conference on Women and Language, April 1994 (forthcoming) concludes that men and women have gender specific communications on MOOs. For an analysis of bulletin board conversations that reaches the same pessimistic conclusions see Susan C. Herring, "Gender and Democracy in ComputerMediated Communication," Electronic Journal of Communications 3: 2 (1993). Herring wants to argue that the Internet does not foster democracy since sexism continues there, but she fails to measure the degree of sexism on bulletin boards against that in face-to-face situations, nor even to indicate how this would be done. The essay may be found at info.curtin.edu.au in the directory Journals/curtin/arteduc/ejcrec/Volume_03/Number_02/herring.txt.] The disadvantages suffered by women in society carries over into "the virtual communities" on the Internet: women are underrepresented in these electronic places and they are subject to various forms of harassment and sexual abuse. The fact that sexual identities are self-designated does not in itself eliminate the annoyances and the hurts of patriarchy. The case of "Joan" is instructive in this regard. A man named Alex presented himself on a bulletin board as a disabled woman, "Joan," in order to experience the "intimacy" he admired in women's conversations. Van Gelder reports that when his "ruse" was unveiled, many of the women "Joan" interacted with were deeply hurt. But Van Gelder also reports that their greatest disappointment was that "Joan" did not exist. [. Lindsy Van Gelder, "The Strange Case of the Electronic Lover," in Charles Dunlop and Rob Kling, eds., Computerization and Controversy (New York: Academic Press, 1991) p. 373.] The construction of gender in this example indicates a level of complexity not accounted for by the supposition that cultural and social forms are or are not transferrable to the Internet. Alex turned to the Internet virtual community to make up for a perceived lack of feminine traits in his masculine sexual identity. The women who suffered his ploy regretted the "death" of the virtual friend "Joan." These are unique uses of virtual communities not easily found in "reality." Still in the "worst" cases, one must admit that the mere fact of communicating under the conditions of the new technology does not cancel the marks of power relations constituted under the conditions of face-to-face, print and electronic broadcasting modes of intercourse.

Nonetheless the structural conditions of communicating in Internet communities do introduce resistances to and breaks with these gender determinations. The fact of having to decide on one's gender itself raises the issue of individual identity in a novel and compelling manner. If one is to be masculine, one must choose to be so. Further, one must enact one's gender choice in language and in language alone, without any marks and gestures of the body, without clothing or intonations of voice. Presenting one's gender is accomplished solely through textual means, although this does include various iconic markings invented in electronic communities such as, for example, emoticons or smilies [ :-) ]. Also one may experience directly the opposite gender by assuming it and enacting it in conversations. [. One example of education through gender switching is given by K.K. Campbell in an e-mail message entitled, "Attack of the Cyber-Weenies." Campbell explains how he was harassed when he assumed a feminine persona on a bulletin board. I wish to thank Debora Halbert for making me aware of this message.] Finally the particular configuration of conversation through computers and modems produces a new relation to one's body as it communicates, a cyborg in cyberspace who is different from all the embodied genders of earlier modes of information. These cyborg genders test and transgress the boundaries of the modern gender system without any necessary inclination in that direction on the part of the participant. [. For an excellent study of the cultural implications of virtual communities see Elizabeth Reid, "Cultural Formations in TextBased Virtual Realities" an Electronic essay at ftp.parc.xerox.com in /pub/Moo/Papers also appearing as "Virtual Worlds: Culture andImagination," in Steve Jones, ed., Cybersociety (New York: Sage, 1994) pp. 164-183.]

If Internet communication does not completely filter out preexisting technologies of power as it enacts new ones, it reproduces them variably depending on the specific feature of the Internet in question. Some aspects of the Internet, such as electronic mail between individuals who know each other, may introduce no strong disruption of the gender system. In this case, the cyborg individual does not overtake or displace the embodied individual, though even here studies have shown some differences in self-presentation (more spontaneity and less guardedness). [. In "Conversational Structure and Personality Correlates of Electronic Communication" Jill Serpentelli studies the differences in communication pattern on different types of Internet structures. (Electronic essay at ftp.parc.xerox.com in /pub/Moo/Papers) Sara Kiesler, Jane Siegel, Timothy McGuire, "Social Psychological Aspects of Computer-Mediated Communication," in Charles Dunlop and Rob Kling, eds., Computerization and Controversy (New York: Academic Press, 1991) pp. 330-349 report that spontaneity and egalitarianism are trends of these conversations.] From e-mail at one end of thespectrum of modern versus postmodern identity construction, one moves to bulletin board conversations where identities may be fixed and genders unaltered but where strangers are encountered. The next, still more postmodern example would be that where identities are invented but the discourse consists in simple dialogues, the case of "virtual communities" like the Well. Further removed still from ordinary speech is the Internet Relay Chat [. For a fascinating study of the IRC see Elizabeth Reid, "Electropolis: Communication and Community on Internet Relay Chat." an Electronic essay at ftp.parc.xerox.com in /pub/Moo/Papers also published in Intertek 3:3 (Winter 1992) pp.7-15.] in which dialogue occurs in real time with very little hierarchy or structure. Perhaps the full novelty enabled by the Internet are the Multi-User Dimensions, Object Oriented or MOOs, which divide into adventure games and social types. More study needs to be done on the differences between these technologies of subject constitution.

On the MOOs of the social variety, advanced possibilites of postmodern identities are enacted. Here identities are invented and changeable; elaborate self-descriptions are invented; domiciles are depicted in textual form and individuals interact purely for the sake of doing so. MOO inhabitants, however, do not enjoy a democratic utopia. There exist hierarchies specific to this form of cyberspace: the programmers who construct and maintain the MOO have abilities to change rules and procedures that are not available to the players. After these "Gods" come the wizzards, those who have acccumulated certain privileges through past participation. Also regular members are distinguished from ìguestsî who have fewer privileges and fewer skills in negotiating the MOO. [. I wish to thank Charles Stivale for pointing this distinction out to me and for providing other helpful comments and suggestions.] Another but far more trivial criterion of political differentiation is typing skill since this determines in part who speaks most often, especially as conversations move along with considerable speed. Even in cyberspace, assymetries emerge which could be termed "political inequalities." Yet the salient characteristic of Internet community is the diminution ofprevailing hierarchies of race, [. See Lisa Nakamura, ìRace In/For Cyberspace: Identity Tourism and Racial Passing on the Internet î in Charles Stivale, ed. Works and Days, 25-26 (Spring/Fall 1995) pp. 181-193.] class, age, status and especially gender. What appears in the embodied world as irreducible hierarchy, plays a lesser role in the cyberspace of MOOs. And as a result the relation of cyberspace to material human geography is decidedly one of rupture and challenge. Internet communities function as places of difference from and resistance to modern society. In a sense, they serve the function of a Habermasian public sphere without intentionally being one. They are places not of the presence of validity claims or the actuality of critical reason, but of the inscription of new assemblages of self-constitution. When audio and video enhance the current textual mode of conversation the claims of these virtual realities may even become more exigent. [. For a discussion of these new developments see "MUDs Grow Up: Social Virtual Reality in the Real World," by Pavel Curtis and David A. Nichols (Electronic essay at ftp.parc.xerox.com in /pub/Moo/Papers)] The complaint that these electronic villages are no more than the escapism of white, male undergraduates may then become less convincing.

Cyborg Politics

The example of the deconstruction of gender in Internet MOO communities illustrates the depth of the stakes in theorizing politics in the mode of information. Because the Internet inscribes the new social figure of the cyborg and institutes a communicative practice of self-constitution, the political as we have known it is reconfigured. The wrapping of language on the Internet, its digitized, machine-mediated signifiers in a space without bodies, [.On this issue see the important essay by Hans Ulrich Gumbrecht, "A Farewell to Interpretation" in Hans Ulrich Gumbrecht and K. Ludwig Pfeiffer, eds., Materialities of Communication, trans. William Whobrey (Stanford: Stanford University Press, 1994) pp. 389-402.] introduces an unprecedented novelty for political theory. How will electronic beings be governed? How will their experience of self-constitution rebound in the existing politcal arena? How will the power relations on theInternet combine with or influence power relations that emerge from face-to-face relations, print relations and broadcast relations? Assuming the U.S. government and the corporations do not shape the Internet entirely in their own image and that places of cyberdemocracy remain and spread to larger and larger segments of the population, what will emerge as a postmodern politics?

If these conditions are met, one possibility is that authority as we have known it will change drastically. The nature of political authority has shifted from embodiment in lineages in the Middle Ages to instrumentally rational mandates from voters in the modern era. In each case a certain aura becomes fetishistically attached to authority holders. In Internet communities such aura is more difficult to sustain. The Internet seems to discourage the endowment of individuals with inflated status. The example of scholarly research illustrates the point. The formation of canons and authorities is seriously undermined by the electronic nature of texts. Texts become "hypertexts" which are reconstructed in the act of reading, rendering the reader an author and disrupting the stability of experts or "authorities." [. "The Scholar's Rhizome: Networked Communication Issues" by Kathleen Burnett (kburnett@gandalf.rutgers.edu) explores this issue with convincing logic.] If scholarly authority is challenged and reformed by the location and dissemination of texts on the Internet, it is possible that political authorities will be subject to a similar fate. If the term democracy refers to the sovereignty of embodied individuals and the system of determining office-holders by them, a new term will be required to indicate a relation of leaders and followers that is mediated by cyberspace and constituted in relation to the mobile identities found therein.

Notes :

This document was produced using HTML Transit


**** Discussion:
- What's at stake?
- david -- not much maybe?
- back to whatthe publis sphere is?  xorg2b
