#+DATE: [2013-01-24 Thu 10:25]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: tools
#+TAGS: tips, wordpress, 
#+DESCRIPTION:
#+TITLE: Back To Wordpress, People!

Well, here we are again, with just a few minutes to go before class and I'm still not sure what we'll be doing exactly!  The point of this week's class is to give you a little push to start (re-)exploring wordpress as you get ready to learn more for your projects.  You already know [[http://2012.hackinghistory.ca/labsnotes/lab-04-getting-started-with-wordpress/][the basics]]: Wordpress is an extensible MS with two main kinds of extensions:

- [[https://wordpress.org/extend/themes/][Themes]], which mostly control the layout, design and presentation of the site, but can have lots of whirligigs and features in addition
- [[https://wordpress.org/extend/plugins/][Plugins]], which add new functions to your site -- such as the ability to add a Twitter feed or use a Google Map

There's also a third category: [[https://codex.wordpress.org/Post_Types#Custom_Types][Custom Post types]], also called Custom Content Types.  These are new categories of data that you define, and instrut Wordpress to handle differently from the default data types (such as posts, pages, and "media").  

To get started, you will want to choose a theme that is close to the layout you're hoping for, and modify it to match your desires.  And you'll have to add functionality by installing new plugins; and when they don't quite do what you ant, we'll have to work together to either modify them or write new ones that do what you want.  

** Themes
This is where most of you will want to start -- you want to have a site that can at least display your working data.  Two immediate concerns:
- Backwards compatibility:  any newer themes use features that don't reender well in older browser & on older devices.  You have to decide (1) how important these devices are to you and (2) how you will deal with the incompatibilities (usually by using some kind of "fallback" system.
- Forwards Compatibility:  the web is changing fast and an increasing percentage of web traffic goes through mobile devices -- already in Canada I'm pretty sure it's a majority.  Older websites display quite poorly on these devices.  To work well with these devices you need to work with at least some of the HTML5 & CSS3 features -- like "responsive" design.  

My immediate suggestion to take a look at some of the HTML5, responsive "framework" themes -- these don't have tons of features built-in, but they are built to help you build your own theme the way you want it.  I have a bunch of these installed now, and meant to put a list here but will do so in very short order!  


** Plugins
Custom Content Manager
