#+BLOG: hh
#+POSTID: 441
#+TITLE:     Tools
#+AUTHOR:    Matt Price
#+EMAIL:     matt.price@utoronto.ca
#+DATE:      2011-10-27 Thu
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
* Tools for Hacking History
As we go through the year, you'll need to learn about some or all of these tools.  Explore them when you have a chance
** Firefox
   Mozilla Firefox is still the most popular open-source browser and, despite Chrome's advances, in many ways the coolest.  Some of our assignments work best with Firefox, so you should install it.  We will also, from time to time, suggest plugins that integrate with Firefox.  [[http://getfirebug.com][Firebug]] and [[http://www.zotero.org/][Zotero]] are probably the most important.
** FTP and/or SSH clients
When you run a webserver, you need a way to move files from your local hard drive to the server. The most common way to do this is with an [[http://en.wikipedia.org/wiki/FTP_client][FTP]] client. There are loads of these, but one popular client is [[http://filezilla-project.org/][filezilla]]. There is also a [[http://fireftp.mozdev.org/][Firefox extension]] that lets you run FTP within your web browser, if that feels more familiar.  

I myself prefer to work from the command line.  For this I use the [[http://en.wikipedia.org/wiki/Secure_Shell][ssh]] program.  Again, there's a [[https://addons.mozilla.org/en-US/firefox/addon/firessh/][firefox extension]] that lets you run ssh entirely in your browser -- if you're not running Unix that may be the most convenient way to do things.  
** Zotero
In the course of your research projects you will accumulate lots of sources, just as you would in a normal research project. These days, we find most of our sources on the web, but older techniques for managing sources -- notecards & so forth -- don't integrate easily with this workflow.  [[http://zoteor.org][Zotero]] is a great bibliographic tool that will help you manage all of your references from your web browser, and will also let you easily drop them into your documents in Microsoft Word or LibreOffice.  If you want to update a reference, or completely change the style of your citations (from MLA to Chicago Manual of Style, vice-versa, or into any of several hundred freely-available journal styles), you can do that, too, at the click of a button.  You can also share references with each other or with others using Zotero groups.  To get started:
- [[http://www.zotero.org/download/][Download Zotero]]. I prefer the [[http://www.zotero.org/support/3.0][Beta]]. Be sure to download both the Zotero program and the connector for MS Word or Libreoffice/OpenOffice, depending on which you need. If you're using Beta, get the ocnnectors for Chrome and/or Safari, too.  Follow the installation instructions.
- [[http://www.zotero.org][Get an Account at Zotero.org]] and [[http://www.zotero.org/groups/51961][sign up for our group]].
- Start Zotero and hit the 'sync' button near the top right of the Zotero pane (it's a little curved arrow). You'll be asked for your Zotero ID info; enter it.  The class library should now show up in your library pane (left side of Zotero pane).
- Read the [[http://www.zotero.org/support/][documentation]] and/or [[http://www.zotero.org/support/screencast_tutorials][watch the screencasts]]
- flow like a ninja around all your citation needs.
** Dropbox or alternative.  
You will often need to share files with each other. For this a service like [[http://www.dropbox.com][Dropbox]] is essential.  Get it, use it, love it.  If you're uncomfortable with Dropbox's security paradigm, consider using Sparkleshare or spideroak.
** Version Control Software
The One True Way to code and/or run a project is to use version control software that tracks your changes and allows you to revert, merge, and otherwise manipulate them, whie also potentially storing them on a server & enabling collaboration.  The most powerful of these is probably [[http://git-scm.com/][git]], but there are many others. Here's a [[http://hoth.entp.com/output/git_for_designers.html][quick intro]].  Consider using one of the many [[http://git-scm.com/tools][GUI]]'s available for git.  From time to time I'll use [[http://github.com][github]] to share project files with you; if you feel up to it, you can learn how to do all kinds of complex operations on those files, or you can justdownload the .zipped repository files.
** Text Editor
From time to time you will need to edit code  For this you will need a real text editor -- and not just NotePad.  Many windows users like [[http://notepad-plus-plus.org/][NotePad++]], and [[jedit.org][jEdit]] is a great cross-platform option. Google "Code Editor" for more options.  Remember [[http://jsbin.com/][JSBin]] for quick tests of code; if you are doing a project with lots of references to outside files, though, this won't work all that well. [[http://jsfiddle.net][JSFiddle]] is also great, and is maybe more flexible than JSBin.  No live updates and it's a little harder to enable debugging.    
** Coding resources
Most of the technical skills you'll learn in this class you can teach yourself (that's mostly how I did it).  Here are some links to get you started:
- HTML:
  - [[https://developer.mozilla.org/en-US/learn/html][MozDev Links Page]]
  - [[http://w3schools.com/html/default.asp][w3schools HTML tutorials]]
- Javascript
  - [[http://www.w3schools.com/js/][W3 Schools Javascript tutorial]]
  - [[https://developer.mozilla.org/en-US/learn/javascript][MozDev resources]]
- P2PU's [[http://p2pu.org/en/schools/school-of-webcraft/][School of Webcraft]] for all of the above
** Delicious
** Twitter
