#+DATE: [2012-08-18 Sat 16:29]
#+POSTID: 59
#+TITLE:     Class Project Guidelines
#+AUTHOR:    Matt Price
#+EMAIL:     matt.price@utoronto.ca
#+PARENT: Assignments,
# #+STARTUP: customtime
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS: toc:1 H:3 num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
# #+OPTIONS:   H:3 num:nil toc:nil  @:t ::t |:t ^:t -:t f:t *:t <:t
# #+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
# #+INFOJS_OPT: view:nil toc:3 ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
# #+EXPORT_SELECT_TAGS: export
# #+EXPORT_EXCLUDE_TAGS: noexport
# #+LINK_UP:   
# #+LINK_HOME: 
#+ODT_STYLES_FILE: "/home/matt/.emacs.d/odt-syllabus-export.odt"
#+CATEGORY: 

The class project, which will occupy most of the class's second semester, is a substantial collaboration between a small group of students and a community organization, on a project of mutual interest.  In almost every case the project will be a Wordpress website, though I am in principle open to other types of projects -- for instance, exhibits or ambient installations. The intention is to create something of lasting value to yourself, the organization, and the community it serves, so that your work endures beyond the temporal scope of the class.  The project is worth 45% of your final mark, but this percentage is distributed between various parts of the project.  A high premium will be placed on timely, regular progress made towards intermediate goals, to help make sure that these complex and difficult projects come to fruition.  Some of you have already been thinking about projects; this is great and /you should continue to do so/.  You will work in small groups of 2-4; in a class of this size there are ose challenges to group work, but there are substantial benefits to working together, especially when charting unknown territory.  
* Collaboration and Service
We should perhaps distinguish between two kinds of working together for this project.  On the one hand, you will be working closely with your peers.  As a result, you have an additional responsibility to your working group -- your lapses affect them too.  You'll also need to be sure to communicate clearly and effectively with each other, both electronically and in person.  Be sure that you know what each of you bring to & get out of the project; and how will you hand the project over.

You will also be working together with an organization that will be depending on you.  In this respect, you act as emissaries of the University and of the course.  You are expected to be respectful, courteous, and responsive.  
* Project Parameters
The finished product should be a polished website or other digital artifact which is directly of use to the partnering organization; it should also be an intellectually honest endeavour which takes seriously the historian's responsibility to tell truths about the past. Your work will, then, be held to a relatively high standard -- I'm asking a lot of you.  You should therefore take pains /not to bite off more than you can chew/.  Your project should be of a manageable scope, and if it's more than your group can do on its own, you should be absolutely sure that your partnering organization has resources to devote to the project either while you work on it, or after the class has finished.  Here are some things you should /not/ attempt to do:
- *do not design your own web framework.*  Instead, you should use [[http://www.wordpress.org][Wordpress]], whih we will be learning about together in class.  If you have a prior expertise in some other framework or in web design, you should discuss this with me immediately. Past experiences with non-Wordpress technologies have been extremely problematic.  
- *do not attempt to tell the story of a major event or historical figure.*  Do not attempt to create a digital archive of the Holocaust, or a definitive documentary history of the War of 1812, or an oral history archive of the immigrant experience in Toronto.  These are /areas of interest/, not /topics for a project/.  Narrow your subject as much as you possibly can; then talk about it with me and we will narrow it down further.  
- *do not strike out entirely on your own.*  You will need some support from outside -- that is one of the main reasons to have a community partner.
- *do not put /anything/ off till the last minute.*  In a complex project like this you will be surprised at the number of tasks there are to accomplish.  In particular, you'll gain a lot by attacking your organizational tasks as early as possible.
* Examples
Last year's projects are linked to from [[http://2011.hackinghistory.ca/student-projects/][last year's course website]].  Perhaps the most impressive of these is "[[http:microscope.hackinghistory.ca][Neighbourhood Under the Microscope]]".  Please note that these sites were made by students with no prior technical experience; if you're in that category they may look daunting right now, but don't be discouraged, you'll learn what you need to in time to make something really cool.  
* Technical Parameters
- Web hosting:  Your project should be housed either in your own webspace or on the class server.  You will need to become familiar with FTP or other transfer protocols in order to edit the project files, and you will need a text editor or online tool such as   You might think about hosting a version on [[http://www.github.com][GitHub]] or a similar service, so that you can make initial changes on your home computer before committing them to the public site.  It is very important that files be publicly accessible, so that your partners and I can help you with design or programming challenges you may encounter. This will also ensure that your site 
* Human Subjects Ethics Review
One of the benefits to a partner is that work done /in the service of that organization/ is exempt from the ethics review process.  If however you conduct interviews, etc. outside of the project you will need to comply with the University's [[http://www.research.utoronto.ca/for-researchers-administrators/ethics/human/][Ethics Review process]]; cf. also  [[http://www.research.utoronto.ca/wp-content/uploads/2009/09/ERO_Guidelines_Manual-2007.pdf][this document]].  The procedure is not terribly onerous but it does take some time so be very serious about this.  
* Grading
#<<grading>>
The final project will be evaluated based on its success in meeting the goals outlined in the proposal, on the integrity of historical analysis, on the aesthetics of the presentation, and on the satisfaction of the community partners with your work.  
| Component      | Due Date | Group/Indiv | % of Course Grade |
| Draft Proposal | Nov. 01  | Indiv       |                 5 |
| Final Proposal | Nov. 29  | Group       |                 5 |
| Interim Report | Feb. 21  | Group       |                10 |
| Final Product  | Apr. 04  | Group       |                20 |
| Partner Report | ---      | Group       |                 5 |
In addition, most of your blog postings in semester 2 will be concerned with your project & your progress on it.  

