#+POSTID: 75
#+DATE: [2010-09-16 Thu 06:29]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: handouts
#+TAGS: administrivia, 
#+DESCRIPTION: 
#+TITLE: The Course Blog

Two of the main themes of the class are: the exploration of digital media as a mode of communicating historical knowledge; and experimentation with the collaborative production of knowledge.  So it's not surprising that, first, the bulk of your assignments are shifted over to the digital realm, in the form of this class blog; and second, that we will be thinking of this website as a platform for a collective exploration of our subject matter.  After [[http://2013.hackinghistory.ca/wp-login.php?action%3Dregister][registering]] for the site, you will be /expected/ to produce one substantive post a week (500 words), and /allowed/ to add as many short 'heads-up' postings as you desire (though for the most part such postings would be better off in the comments section of an existing post).  You will also be expected to comment regularly on your colleagues' (and my own) postings.  
** Due Dates
Unless otherwise noted, blog entries are due 24 hours before the start of the next class.  This is a firm deadline to permit others time to comment on your work, and on occasion to give me a chance to post something after everyone has made their contributions.

** Assignments
Again unless otherwise noted, postings in the first semester take the form of a response to the week's readings or theme.  As with any short response paper the object of the posting is not to summarize, but to engage critically with the texts at hand.  For general guidelines on writing, look [[http://www.writing.utoronto.ca/advice/specific-types-of-writing][here]]. You can also think of these posts as a cross between an [[http://www.quicksprout.com/2009/07/21/how-to-write-a-blog-post/][ordinary blog post]] and a [[http://historyprofessor.org/reading/how-to-write-a-review/][review or response paper]].   We will discuss this further as the semester goes on.  In the second semester, you are expected to post about your project: progress reports, pieces of text you've written for your site, or reflections on other aspests of the project. 

** Grading
Your online contributions constitute 20% of your grade (that's not including your final project and ancillary assignments, some of which will also go through the course blog).  Your weekly blog posts will be evaluated in bulk, but I'll be applying the following criteria (cf. Mark Sample's [[http://www.samplereality.com/2009/08/14/pedagogy-and-the-class-blog/][helpful post]] from which parts of this are derived):
- _4_ Excellent.  Clear, concise analysis, convincingly written, with few spelling or grammatical errors.  Entry has a clear thesis and advances arguments & presents evidence within the limited scope of the assignment to support the thesis. 
- _3_ Good. Entry is still coherent and well-edited, but its arguments are less pointed, convincing, and novel.  Reflects moderate engagement with the topic. 
- _2_ Subpar.  Argument is flimsy, posting is mostly a summary or rehashing of readings.  Reflects passing engagement with the topic.
- _1_ Inadequate.  Unstructured, error-ridden, no argument to speak of.  Shows no engagement with the topic.
- _0_ No Credit.  Failed to post or made only a token effort.  

The better your postings, the more exciting and engaging this class will be for everyone.  So please approach this part of the class in good faith and take it seriously.  
