#+POSTID: 1864
#+DATE: [2012-01-19 Thu 10:47]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: maps, georeferencing, tools
#+TAGS:
#+DESCRIPTION:
#+TITLE: Georeferencing -- References & Tips

Next week's class will take place in the Map and Data Library, on the 5th floor of Robarts.  PLEASE ARRIVE PROMPTLY -- we are presuming on the generosity of a very sought-after expert, Marcel Fortin (thanks Marcel!).  Class, which may or may not take a full 3 hours, will focus on [[http://en.wikipedia.org/wiki/Georeference][georeferencing]].  We use the term in a fairly limited way, meaning "matching a historical map to GIS co-ordinates", but it's worth thinking for a moment about the technical definition.  To 'georeference' something means to locate it in space.  If I have one representation of space, and you have another, then in order for us to co-ordinate our representations we need a third object -- a set of co-ordinates -- to which we then map BOTH of our representations.  Then we can mediate between representations by making reference to the common, underlying co-ordinate system.  

Not long ago this type of practice would have been pretty distant from the kinds of activities an undergraduate would undertake, but it's become worthwhile for us.  Why? Because services like Google Maps (and there are others -- [[http://openlayers.org/][OpenLayers]], for instance) offer increasingly easier integration with all kinds of data sources.  So, for instance, it is possible to chart wordpress posts on a map; and as you know, I'm, er,  working on a wordpress plugin for timeMap, which works with google maps.  But it doesn't make sense to chart historical data on contemporary maps; so it would be nicer to use a sophisticated GIS-driven system -- like google Maps -- with a representation of space that shows the terrain as it likely was in the past.  In order to do this, we need to take that historical representation and map it onto our underlying co-ordinate system.  This is a difficult and complex task, but fortunately, there are programs that have been specifically designed to help us accomplish it.  In our workshop next week, we will learn the basics of georeferencing with [[http://www.esri.com/software/arcgis/index.html][ArcGIS]] -- the industry standard -- and also within Google Earth. If there's time, you'll also be introduced to Quantum GIS, an Open Source tool that will allow you to georeference almost a well as ArcGIS, but at home (to use Arc GIS, you will need to work at a licensed workstation on the 5th floor of Robarts).  

In order to prepare for our meeting, you should familiarize yourself with the main concepts of Georeferencing and, if possible, experiment with some of the tools involved.  It would also be GREAT to choose a map to georeference; if you find one, please bring it class on a USB key or put it in a web-accessible location (e.g. Dropbox) so you can experiment with georeferencing it directly after the workshop, before you forget what you've learned.  

The following links are meant to get you started: 

- [[http://help.oldmapsonline.org/georeference][Old Maps Online]] has a collection of links and, in particular, a link to their online tool [[http://www.georeferencer.org/][georeferecer]] which might be of interest, and has a useful youtube video on the front page.
- [[http://code.google.com/apis/kml/documentation/kml_tut.html][Google's KML documentation]], which will tell you what a KML file is and what can be included in it.
- [[http://www.whatwasthere.com/][What was There]] won't really teach you much about georeferencing but will show you what can be done with it -- some pretty cool stuff actualy, though not especially scholarly.
- [[http://www.qgis.org/][Quantum GIS Project]] provides a pretty good gentle introduction to GIS intheir documentation section; and you can download the software and try it out
- Another interesting project is [[http://www.maptiler.org/][Map Tiler]] -- not likely to be the right choice for your projects, but another example of how georeferenced maps can make for really neat user interfaces.  

Add any other resources you find in the comments section, so your colleagues can find them.  
