#+POSTID: 54
#+DATE: [2014-09-05 Fri 16:52]
#+TITLE:     Project Proposal
#+AUTHOR:    Matt Price
#+EMAIL:     matt.price@utoronto.ca
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 
#+PARENT: Class Project Guidelines, 

The project kicks off at the end of Fall semester with a formal proposal and presentation.  The written proposal will be submitted not only to me, but to your partner as well, so it is an important document.  

* What is this project proposal thing for anyway?

A project proposal is a roadmap and guide to the final project. You yourself will consult it many times over the course of the semester, as you struggle to keep track of what you have promised to do. Your partner (who will respond to your proposal with feedback & perhaps call for some changes) will also refer back to the proposal when you present them with the final product. so it's a very important document.
But what goes in it?

The proposal is a complicated document that walks a fine line: it should present an exciting vision without promising too much; it should present a compelling historical narrative even though your real knowledge about the subject is still somewhat limited; it should propose a look for the website even though what you produce will certainly look different. Here is what I expect from this proposal document (due next week, if you can believe it!):

- a substantial piece of writing that describes your goals for the site in some (but not too much) detail. More on that below. 
- a preliminary bibliography, of as many different sources as you can muster. Light annotation is a plus (not a paragraph-long description of each source, as in a formal "annotated bibliography", but a sentence or two describing the value of the work to your project). You're going to end up doing a lot of research for this project, so "as many sources as you can muster" should not be 5 or 6, but more like 20 or 30.
- mockups of representative site pages – this means the front page, a couple of the main pages you plan, and some pages for the main datatypes (posts, events, historical photographs, oral history pages, whatever).

* The Main Proposal: defining your project

This is a substantial document (2000 words?) which the group should produce together (so, divide up the work – see below). Here's what it should cover:

- Scope/Introduction :: What is the topic of your website, and what kinds of information will it provide? Why is it useful/important/interesting? Who is the partner, and how does it benefit them? What topics/tasks are out of scope? this latter question, which is sometimes hard to answer, is an important one to think about – setting yourselves limits is an important part of making the project feasible. Your partner will be reading this, so emphasize that you wil lbe uilding a website based onteh Wordpress framework, with light modifications & additional plugins.
- Audience :: who wants to visit this site, and what will they do there?
- Structure and Presentation :: Describe the layout and structure of your website as well as you can. Refer to the mockups, and feel free to draw diagrams (showing, e.g., how people are likely to move around the site, or what the hierarchical relation of pages is, etc.). Describe in some detail what kinds of information each type of page will have. In your description, say why you chose this particular organizational structure – why are these the most important navigational axes for your site?
- Research Methods :: What do you have to learn, and how will you do it? E.g., mention that you will do oral histories if you intend to; or that your will access architectural records in the Toronto Archive, if you intend to do that. consider also what the most interesting historiographical questions are – what are the puzzles that interest/motivate you?
- Challenges :: Describe as specifically as you can the difficulties you expect to face, and how you hope to overcome them. If your group is missing skills that you need, again, be as specific as you can about what you need to know and how you might address this need.
- Roadmap :: When do you expect to get your work done? The final website is due in class Apr. 5. You will need to get something done every week until then (!) to make this project great. What are your goals for each week? Also, who is doing what? each person in the group should have specific responsibilities to which they commit. These may change around a bit, and you will all help each other with your assigned tasks, but laying out expectations in writing makes it more likely that things will get done.
- Working with your Partner :: Describe in as much detail as possible the relationship with your partner.  Include e.g. discussion of:
  - How your work will benefit your partner
  - What resources will your partner bring to the project
  - What plans you have made for turning the project over to your partner

* Mockups
In addition to the main proposal, you should include mockups of some of the main pages on the website, e.g., the front page and the layout for various content types.  This is a proposal, and we understand that things will change as yougo forward.  

I recommend using the 960 grid paper we used in our mockup class. I'll bring some in, and you can also download it from here. Refer back to your excellent reading – your mockups will work best if they indicate some (but not all) of the interactions you expect people to have with the site.

* Bibliography

I really recommend that you use a reference manager to deal with your citations; and of the available options, I strongly recommend Zotero or possibly Mendeley. You can easily set up a group bibliography, and also generate an annotated bibliography with almost no effort. Highly recommended. For more on Zotero see the Tools page.

* Presentation
The final week of classwill be devoted to project presentations, which will form a part of your mark for the proposal. Consider it practice for presenting to your partner.  You should prepare a set of slides thatruns through the basic ideas, organization, and look & feel of your website; it should be brief, some 20 minutes, with ample time for questions at the end. The tone should be formal, in contrast to most of our class meetings.  

