#+POSTID: 61
#+DATE: [2012-08-18 Sat 16:05]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: assignments, 
#+TAGS: oral-history, handouts, 
#+DESCRIPTION: 
#+PARENT: Assignments, 
#+TITLE: STA 03 -- Oral History

Depending on the nature of your project, it may benefit greatly from some kind of oral history component.  In this assignment you will conduct a short interview with a friend or classmate on the subject of "Making History", and write a brief summary of what you learned from the experience.  The person you interview should be someone who has 

As part of the research for the project, each of you will conduct an interview with a friend, family member or associate about their experience of the event.  After the interview you will write a short reflection on the experience in light of the readings we have already done on oral history techniques. Post your reflection to the blog as per normal but please be sure to restrict access to the Student group, and take special care not to compromise the anonymity of your source (as we are not conducting the full ethics review that would otherwise be necessary).  Bring your recordings to class with you and we will discuss the process in lab.  

Be sure your subject KNOWS IN ADVANCE what your plans for the interview are (i.e.:  that you will be writing about it, but not fundamentally about the CONTENT of the interview; that your response will be shared with your colleagues; that the interview will NOT be made public).

The purpose of this STA is to get you thinking about the possibilities inherent in the practice of oral history, by briefly undertaking an oral history interview and reflecting on the experience.  

** Lead a brief Interview
Find a friend and take about 20 minutes to ask him/her some questions about her/his life growing up.  Before the interview, review what you know about this person and what are likely to be the most interesting topics; be prepared to elicit conversation about those topics, perhaps by making a list of questions in advance.

** Reflect
After you're done, write a brief (500 wordish) report on the experience.  Do NOT post it to the web, as it will be almost impossible for your to say anything of substance without making some reference to the content of the interview, and there are strong ethical reasons not to do that in a public forum without permission.  Instead, bring it to class and we can perhaps take a few moments to discuss these  next week.  In your response, consider the following questions:
- what was the interviewing experience like?  Did you enjoy it?
- how reliable a source is your friend?  Did you retrieve the kind of information you wanted to?
- how might you make use of an oral history in a digital format, like a website?
- any further methodological/epistemological/ethical concerns that you have post-interview.  

1.  Preparing for the Interview
You should know the following going into the interview: 
-Name of interviewee
-What do you already know about their experience
-Dates and times of events in question- when did it occur, when were you there.
-Think about how to create rapport or trust- make it clear why are we doing this interview, what are they consenting to, a contract; 
During the interview, ask set questions, broad questions first, then follow up on answers in order to show you're listening, to obtain details and to clarify and build rapport, then return to  your questions.  Here is a skeletal structure for the interview, TO WHICH YOU ARE NOT BOUND.  
1) Why were you there?
2) What was your inital reaction, and feeling
3) Tell me what happened when you were there, in your own words.
4) What was the pivotal turning point or event for you?
5) Is there anything else you'd like to tell me about that day?
6) Did it change the way you view your city at that moment? 
7) Did it change your view of your city since the event?

2. Interview length and format
Be careful not to let the interview go on too long, as you'll need to listen to it later!  30 minutes will be more than enough; 10 minutes is probably a minimum length to get something interesting out of the interview.  

Remember that your questions are just a guide -- be attuned to moments of engagement on the part of our subject, and follow them up when they occur.  
Re-read Anderson and Jack, "Learning to Listen." 
If you have time, also read [[http://www.transom.org/guests/review/200804_elizabeth_arnold/][Elizabeth Arnold's Interviewing Manifesto]] and any other great guide you can find on the excellent on [[http://www.transom.org][Transom]].  

3. Post-Interview Reflection (this is the most important part).

Please answer the following questions with no more than 250 words each.  

Choose one of the following:
1.    What was the most negative aspect of your interview?
2.    What did you do wrong (Stefano)?
3.    Is there something you should have extrapolated upon in the interview?
4.    Were you too rigid in adhering to your questions?
5.    Misc.

Choose one of the following:
1.    Were you surprised by anything?
2.    What was the most interesting part of the interview?
3.    Was your interviewee engaged in the process?
4.    Was there a friction between the lens through which you tried to ask the questions versus the lens through which the interviewee was portraying their story?

You have to answer this one, it's the law:
1.    In creating an oral history did you find it useful as a medium? What are the limitations and challenges? Benefits?

