#+POSTID: 55
#+PARENT: Partners
#+TITLE: Guidelines For Community Partners
#+DATE: [2010-09-11 Sat 07:15]
Institution: University of Toronto – St. George Campus

Department: History

Contact Information:  Matt Price



* COURSE TITLE: Hacking History

On behalf of the Department of History at the St. George campus of the University of Toronto, I would like to invite you to participate as a partner for a fourth-year undergraduate course, “Hacking History”  during the 2011-12 academic year.  “Hacking History” is a year-long advanced undergraduate seminar in which students spend their first semester learning how to tell stories and convey historical information through digital media, and then apply that knowledge in the second semester through collaboration with a community organization.  In the past that collaboration has generally taken the form of a    Students will learn about the history of the world-wide web and how it has changed the way that knowledge is produced and accessed.  They will also learn basic techniques of digital and multimedia storytelling, including topics such as web design and oral history.  

Community partnership is basic to the class's learning model and has had ex
The service-learning placement in the second semester is crucial to the objectives of the class, as students will use their new skills to build a substantial historical website or exhibit.  The course has as one of its primary objectives to help build bridges between the University and community organizations, making the history Department's expertise available to a wider public, while at the same time making the public's own knowledge and experience more accessible to students and teachers at U of T.  

** Service-Learning Placements

Our students are history majors with well-developed research, writing, and design skills.  They can offer you, the community partners, assistance in conceptualizing and bringing to fruition projects of a historical nature that can both serve your community and raise your organization's profile on the world-wide web.  Ideally, organizations will find our students capable and enthusiastic partners in the exploration of your community's history.  Our students will take this opportunity to hone their skills and work on a project of enduring value.  They will be evaluated both on the final collaborative product and on their regularly-produced reflections on the experience.  The objective of the placement is to give students real-world experience in the application of the skills they have learned in class and in the course of their undergraduate training, while at the same time encouraging them to find ways to participate in civic society and self-education for the rest of their lives.

** The Students

The course enrols a maximum of 16 students who can be assigned individual or group placements.  Students are expected to complete at least 4-6 hours of service work – mostly research and development of the final product – starting January 3 and ending April 8, but will begin planning their projects much earlier, certainly by the end of October.  Students can work individually or in groups of 2-4 persons.  Community partners are invited to contact us with their ideas at the addresses below and/or fill out our web contact form.  We welcome any and all ideas, with the sole restriction that organizations must have the financial resources to support projects once they are completed (by hosting websites, staging exhibitions, etc), and the enthusiasm to offer thematic guidance to students as they work.  

** Contact Information

Matt Price
History Department, University of Toronto
matt.price@utoronto.ca
416-516-8194


** Sample Project Ideas
+ Your organization serves an immigrant community with a wealth of stories about the migration experience.  Hacking History students can help you collect those stories, place them in the context of changing political and economic conditions in Canada and the country of origin, and build an oral history website to make all of this information accessible to your community and the broader public.
+ Your organization serves a neighbourhood of Toronto.  Hacking History students can research the neighbourhood's history and build a 'locative' web exhibit that links map locations to important events in the neighbourhood's formation. 
+ Your organization itself has a long and storied past.  Our students can help research that history and make it available on the web.
+ You are already working on a large-scale historical documentary or other project.  Our students can help you with research, scripting, and an accompanying website.
