#+POSTID: 297
#+DATE: [2010-09-30 Thu 06:05]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: "Pre-class notes", 
#+TAGS: html, 
#+DESCRIPTION:
#+PARENT: Syllabus,  
#+TITLE: Notes on Hypertext

First thanks for the very interesting group of papers this week.  A few observations about them:

When reading Bush's article, bear in mind, first, just how science-fictional this all sounds in the 1940's, and second, just who this is speaking to us.  Bush was probably the most important administrative scientist of the era.  As a professor of electrical engineering at MIT, Bush is now best-knwon for the invention of the [[http://en.wikipedia.org/wiki/Differential_analyser][differential analyser]], a very fun device now fetishized for its role in the history of computing.  But his most widespread notoriety is for his pivotal role in the construction ofthe Atomic Bomb, about which we can say that it is hard to imagine how it would have been built without him.  "As We May Think" was a relatively lighthearted piece of very little practical significance in Bush's career, which he never really followed up in any substantive way.  But the sense of the possibilities of science come out of this strange and formative era in the history of science.

This time around I'm particularly captivated by the thinking subject pictured in the article: 
#+BEGIN_QUOTE
On the top of the memex is a transparent platen. On this are placed longhand notes, photographs, memoranda, all sorts of things. When one is in place, the depression of a lever causes it to be photographed onto the next blank space in a section of the memex film, dry photography being employed.

There is, of course, provision for consultation of the record by the usual scheme of indexing. If the user wishes to consult a certain book, he taps its code on the keyboard, and the title page of the book promptly appears before him, projected onto one of his viewing positions. Frequently-used codes are mnemonic, so that he seldom consults his code book; but when he does, a single tap of a key projects it for his use. Moreover, he has supplemental levers. On deflecting one of these levers to the right he runs through the book before him, each page in turn being projected at a speed which just allows a recognizing glance at each.
#+END_QUOTE
I can't help feeling that I'm in the lair of a mad scientist, but at the same time I feel like I',m in a suburban "den" where Dad sits alone, smoking his pipe.  There is something extraordinarily /individual/ about this scheme, given that it's meant to provide an account of the /collective/ organization of scientific knowledge.  This seems to me more important than the casual references to a sort of Gibsonesque "jacking-in", or other specific technological advances described by the piece.  There is no real sense, I don't think, of a World Wide Web of information -- no transparent, effortless, anonymous sharing.  In this it differs substantially from our server-mediated version of hypertext.  compare it, e.g., to [[http://www.theshulers.com/whitepapers/internet_whitepaper/index.html#http][the description of http]] in Schuler's piece.  

Berner's-Lee's Semantic Web seems no less Utopian to me than Bush's article though undergirded by a much more robust technological infrastructure and research agenda.  RDF is a real technology now.  But there is something quite unsophisticated in the notion of ontologies defined, negotiated, and mediated almost exclusively by machines.  There is a reason the [[http://www.amazon.com/Being-Time-Martin-Heidegger/dp/0061575593/ref=sr_1_1?s=gateway&ie=UTF8&qid=1285845507&sr=8-1][most important philosophical work on ontology]] belongs to a tradition called "hermeneutics" -- the act of interpretation is complex and essential to the production of meaning.  It's not clear that meaning that resides in machines is still meaning at all.  Moreover, the privacy concerns raised by [[http://www.hackinghistory.ca/2010/09/29/all-aboard-next-stop-the-web-3-0/][Izzy]] are substantive and serious.  There's a lot to think about there and more generally in the future of the web.  

This question of interpretation raises its head again in Ayers' work, e.g. here

#+BEGIN_QUOTE
That said, I cannot help but think about what might come next. Might there be a way, using the electronic environment, to create forms of narrative and analysis that take fuller advantage of the digital archive? Everyone knows the past was wonderfully complex, but seeing the complexity of even a small slice of the past displayed before us can be discomfiting. Historians tend to forget the choices and compromises we make as we winnow evidence through finer and finer grids of notetaking, narrative, and analysis; we suppress detail as the abstracted patterns take on a fixity of their own. A digital archive, by contrast, reminds us every time we look at it of the connections we are not making, of the simultaneity and reflexivity as well as the linearity of the past. May we now be able to, need to, write a new kind of history, a history that can be arrayed and understood in multiple sequences and layers, a history that involves and rewards more engagement on the part of the reader than a book requires or permits? We might call that history, for convenience, "hypertextual," since it would involve linked text in a manipulable electronic environment. Better, less awkward, names may evolve along with the genre. 
#+END_QUOTE
and here
#+BEGIN_QUOTE
Fortunately, the digital archive emphasizes the centrality of evidence and thus presents no challenge to the central demand of the profession. Digital history excels in presenting evidence, enormous amounts of it. 
#+END_QUOTE
This is something all of us will need to think about as we move forward.  I look forward to that now and over the coming weeks.  
