#+POSTID: 472
#+DATE: [2010-10-19 Tue 22:46]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: pre-class-notes, 
#+TAGS: crowdsourcing, 
#+DESCRIPTION: 
#+TITLE: Crowdsourcing the Past

Let's start with this quote from [[http://chnm.gmu.edu/essays-on-history-new-media/essays/?essayid=42][Rosenzweig]]:

#+BEGIN_QUOTE
Can the wiki way foster the collaborative creation of historical knowledge? One promising approach would leverage the volunteer labor of amateurs and enthusiasts to advance historical understanding. Historians have, of course, benefited from the labors of amateurs and volunteers. Think of the generations of local historians who have collected, preserved, and organized historical documents subsequently mined by professional historians. But the new technology of the Internet opens up the possibility of much more massive efforts relying on what the legal scholar Yochai Benkler has called "commons-based peer production." 
#+END_QUOTE

These possibilities are some of the most exciting ones on the web, and I want to be sure we make use of them /but not foolishly/.  Rosenzweig is very cautious in his estimation of the possibilities of open source history; this may be because he was far too reliant on Wikpedia as an example (and also because the Wikipedia he was looking at, in 2006, was far less developed than it is today).  Most of the other articles (leaving aside Aaron Swartz's for now) give examples of interesting collaborations that are mediated by technology.  The search for Steve Fossett, though not remotely historical, is nonetheless interesting because of the way it calls upon a community which is itself created out of an event (Fossett's disappearance) and joins thousands of people together in pursuit of a common goal.  [[http://crisiscommons.org/][Crisis Commons]] is a somewhat similar project, in that it joins like-minded geeks together in an infrastucutre around ocmmon interests which themselves almost emerge form the infrastructure itself.  How can we put this to use in a historical project?  Steve.museum offers some interesting insights, which should be somewhat familiar from our delicious experience: tagging is a fantastic way to involve a wide public in collectively evaluating a work of art or a piece of analysis.  There is a kind of wisdom of the mass which can be captured by such an endeavour, but at the same time an organizational benefit to tags that opens new possibilities for use of a collection (remember [[http://www.theatlantic.com/magazine/archive/1969/12/as-we-may-think/3881/][Vannevar]]?).  We need to think about how to mobilize the communities who care about our projects in similar ways.  Look forward to hearing what you have to say over the next 2 days. 

