#+POSTID: 3183
#+DATE: [2013-02-14 Thu 09:48]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: 
#+TAGS:
#+DESCRIPTION:
#+TITLE: Favicons

This is a very small issue you will want to deal with near the end of your project.  Load your website in a new tab.  Notice that there is a small picture -- an "icon" -- displayed in the tab.  

This picutre is called, for obscure reasons, a "favicon".  Its main use it to help you navigate visually between tabs -- so you just look up at your tab bar and know immediately which tab is the one with your site loaded.  The favicon has to be a file that is somewhere accessible on the web, usually in the root directory of the site.

Our starter theme uses the following line in header.php to find the favicon: 

#+BEGIN_SRC html
	<link rel="shortcut icon" type="image/png" href="<?php echo get_stylesheet_directory_uri(); ?>/favicon.png">
#+END_SRC

Try to read this and understand it.  This is a pretty simple HTML tag, using the [[http://blog.whatwg.org/the-road-to-html-5-link-relations#what][link]] tag and the [[http://blog.whatwg.org/the-road-to-html-5-link-relations#rel-icon][icon relation]] to tell the browser where the favicon is located.  However, there is one tiny php command hidden inside:

#+BEGIN_SRC php
 <?php echo get_stylesheet_directory_uri(); ?>
#+END_SRC

This  command just says to wordpress:  "first, check to see if this is a child theme; if it is, look for the file there; if not, look for the file in the parent theme".  So then, back to the original html:

#+BEGIN_SRC html
	<link rel="shortcut icon" type="image/png" href="<?php echo get_stylesheet_directory_uri(); ?>/favicon.png">
#+END_SRC

and you can see Wordpress will try to find a file called "favicon.png" in the directory themes/required-starter/, and if it can't find it, will try to find the file themes/required-foundation/favicon.png.  So:  right now your favicon.png is the company logo for the developer firm "required".  You will eventually want to replace that with the logo of your client.  The standard favicon format is a PNG file of 32x32 pixels.  So you will want to generate that somehow, eventually.  

OK, tutorial #1 for today.  

