#+POSTID: 36
#+DATE: [2014-09-05 Fri 16:15]
#+BLOG: hh
#+PARENT: 
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: notes
#+TAGS: 
#+DESCRIPTION: 
#+PARENT: Labs+Notes, 
#+TITLE: Lab 01: Understanding HTML

One of the goals of this week is to help you think of the Web as a protocol-driven infrastructure.  The language in which that infrastructure operates is called [[http://en.wikipedia.org/wiki/HTML][HTML]]. Like a traveller in a foreign country, you may not need to be fluent in this language, but if you know just a little bit then you'll be much more comfortable.  In this exercise we will introduce a couple of online tools that will help you understand all of this stuff better:
- One of the main tools for coding exercise throughout the class is an online editor called [[http://jsbin.com/welcome/1/edit][JSBin]].
- The W3Schools website has a cool little tool called "[[http://www.w3schools.com/html/tryit.asp?filename=tryhtml_style][TryIt]]"; if you tried codeacademy and didn't like it, you might want to see if TryIt is a better match.  I encourage you to work your way through their tutorial system, but we will only cover a few basics right now.
- Finally, you may sometimes want to use [[http://thimble.webmaker.org][Thimble]], which is a lot like JSBin but (a) simpler and (b) comes with an incredible built-in help system.  It can't do everything that JSBin can, but it has a very clear, well-designed interface.  

** Tags
An HTML Document is composed of [[http://en.wikipedia.org/wiki/HTML_element][elements]] marked off by [[http://www.w3schools.com/tags/default.asp][tags]].  The elements look like this:  
#+BEGIN_SRC css
<p>This is a paragraph</p>
#+END_SRC
Note the opening and closing tags, which surround the text you want to have marked up.

*** Important tags
Here are a few examples of important tags, though there are many, many more in current versions of HTML.  
**** Document Structure
Certain tags exist solely to lend *structure* to a document.  
#+BEGIN_SRC html -n
  <html>
    <head></head>

    <body>
      <header></header>

      <article>
        <div>
          <span></span>
        </div>
      </article>

      <footer></footer>

    </body>
  </html>
#+END_SRC

**** Text Attributes
Others give instructions for emphasizing text
#+BEGIN_SRC html -n
  <B></B> <strong></strong>
  <I></I> <em></em>
#+END_SRC
**** Text Functions
Still others define pieces of structure in a functional way that generally also affects the way text will look on your screen.
#+BEGIN_SRC html -n
  <h1>This is a top-level Heading</h1>
  <h2>While this is a lower-level heading</h2>
  <p>..and this is a mere paragraph</p>
  <ul>
    <li>This is a list item</li>
    <li>And this is a second item</li>
  </ul>

  <ol>
    <li>this is a different kind of list</li>
    <li>you'll see the differences soon</li>
  </ol>
#+END_SRC

**** Linking
The fundamental, breathtaking feature of the web is its capacity to create links between documents, images, media sources, etc., with absolute disregard for where those resources are physiclaly stored.  THe syntax for making a link is as follows 

#+BEGIN_SRC html -n
  <a href="" target="">Text </a>
  <img src="" alt="" title=""/>
  <video>
    <source src="" type="">
  </video>
  <script src="" lang=""/>
#+END_SRC

Figure out what these mean by browsing on w3schools. Work especially hard at the <a> tag.  Hint:  the standard syntax is <a href="link">Text</a> and there are plenty of instances in the code below.

*** Exercise 0
Navigate to [[http://jsbin.com/onopaz/7/edit][this page]].  This is the JSBin editor, an online tool for inspecting code.  
*** Exercise 1
First, let's quickly compare the text of an old post of mine:

#+BEGIN_QUOTE
The WWW as Public Sphere
Posted on September 21, 2010 by admin

Just a few quick words about the readings this week, which concern the idea of the “Public Sphere“. This phrase is rooted in ideas about enlightenment that stretch at least back to Immanuel Kant. The analyses of Jürgen Habermas (SEP entry), in particular, developed the idea of a sort of virtual space of critical discussion...

Some of the features of this "authentic public sphere" would be 
- a space free from political repression
- a space accessible to all members of society
- a form of discourse in which ideas are evaluated on their own merits exclusively, and not arbitrated based on some set of characteristics of the speaker


#+END_QUOTE

with the HTML code that generates what you would see on your screen if you went to the website from that year: 

#+BEGIN_SRC html -n
<div id="post-77" class="post-77 post type-post hentry category-notes-for-class tag-publicsphere">
					<h1 class="entry-title">The WWW as Public Sphere</h1>

					<div class="entry-meta">
						<span class="meta-prep meta-prep-author">Posted on</span> 
<a href="http://www.hackinghistory.ca/2010/09/21/the-www-as-public-sphere/" title="11:03 am" rel="bookmark"><span class="entry-date">September 21, 2010</span></a> <span class="meta-sep">by</span> 
<span class="author vcard"><a class="url fn n" href="http://www.hackinghistory.ca/author/admin/" title="View all posts by admin">admin</a></span>					</div><!-- .entry-meta -->

<div class="entry-content">
	<span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&amp;rfr_id=info%3Asid%2Focoins.info%3Agenerator&amp;rft.title=The WWW as Public Sphere&amp;rft.aulast=Price&amp;rft.aufirst=Matt&amp;rft.subject=Pre-class notes&amp;rft.source=Hacking History (His495)&amp;rft.date=2010-09-21&amp;rft.type=&amp;rft.format=text&amp;rft.identifier=http://www.hackinghistory.ca/2010/09/21/the-www-as-public-sphere/&amp;rft.language=English"></span>

<div class="sticky_post"><p> Just a few quick words about the readings this week, which concern the idea of the  &#8220;
<a href="http://en.wikipedia.org/wiki/Public_sphere">Public Sphere</a>&#8220;.  This phrase is rooted in ideas about <a href="http://plato.stanford.edu/entries/enlightenment/">enlightenment</a> that stretch at least back to 
<a href="http://en.wikipedia.org/wiki/Immanuel_Kant">Immanuel Kant</a>.  The analyses of 
<a href="http://en.wikipedia.org/wiki/J%C3%BCrgen_Habermas">Jürgen Habermas</a> 
(<a href="http://plato.stanford.edu/entries/habermas/">SEP entry</a>), in particular, developed the idea of a sort of virtual space of critical discussion  </p>

</div>
											</div><!-- .entry-content -->
#+END_SRC

They look pretty different, right?  Now, paste the text-only version into the HTML tab in [[http://jsbin.com/waxufekequte/2/edit][this JSBin page]].  

Figure out how to accomplish the following tasks:
1. Make the title "The WWW and the Public Sphere" into a heading.
2. Add a link to "http://www.hackinghistory.ca/author/admin/" to the word "admin" in the second line.
3. Italicize the date line.
4. Organize the elements so that the appropriate content is nn the <header> tag, and the rest in the "article".

These are all pretty easy, you can figure them out either by inspecting the marked-up version I reproduced here, or following the w3schools HTML tutorials.  
 
** Styles
Styles in HTML are pretty complex, see the [[http://www.w3schools.com/html/html_css.asp][HTML style tutorials]] on w3schools.  Check out their very quick description of [[http://www.w3schools.com/css/css_intro.asp][css]].  
*** Exercise 2
    Go back to your TryIt experiment at w3schools.  Can you make the text render in the same styles that are used by the website?  There's a clue in the <head> element of any page from the site.  Hint: search for "css" in the sourcecode...
** Scripts
Though HTML is the language of the web, modern HTML (HTML 4, HTML 5) have "translators" of a sort that allow other languages to run inside the web page.  this is actually incredibly powerful, and allows amazing things that were unheard of in the early days of the web, like dynamically-generated lists, moving images, the embedding of video and so forth.  You don't have to know how to script (I can't really use javascript, for instance) but you should understand that scripting is what makes a lot of today's web work the way it does.  
*** Exercise 3
Inspect the source code of three complex pages on the web and find every instance of a script tag.  Note anything you think is interesting about it.  

** Some more advanced stuff
If you're way out in front of the class, take a look at [[http://jsbin.com/urobaq/3/edit][some of the exercises]] we [[http://jsbin.com/utinoz/9/edit][did last year]]. Can you figure everything out?  What do you think of the JSBin editor?  

* Hacking your way to HTML mastery!
** Tools!
- *View source.* When you right click on a web page in any modern browser, you will see a 'view source' option.
- *developer tools*.  The Developer Tools for [[https://developer.chrome.com/devtools][Chrome]] and [[https://developer.mozilla.org/en/docs/Tools][Firefox]] are both amazing.  They allow you to temporarily change the code (HTML, CSS, and Javascript) running on any website, and thus test out your ideas for changes.  We will use this tool *A LOT* over the course of the year.  
- *[[http://jsbin.com][jsbin]]*. The awesome real-time html/javascript previewer.
- *Hackasaurus.* Mozilla has a really neat new tool for kids that you might also find useful, called "Hackasaurus X-Ray Goggles.  [[http://www.hackasaurus.org]]

** Tutorials
- [[http://codeacademy.com][Codeacademy]] may have the best intro to HTML sequence
- [[http://w3schools.com/][W3 Schools]] provides excellent tutorials.
- Mozilla's [[http://discourse.webmakerprototypes.org/category/training][Teach The Web]] site has a number of resources
- [[http://hackbook.hackasaurus.org/][The Hackasaurus hackbook]] is another great place to start
- [[https://developer.mozilla.org/en/HTML][The Mozilla HTML Reference]] is where I go when I need a detailed explanation of something.  


** Templates
Finally, just a note on how pages are generated in wordpress out of templates.  Quickly read [[http://codex.wordpress.org/Stepping_Into_Templates][this page]] on the wordpress website.  Can you tell where the template divisions are in a page from our site?  Try inspecting the sourcecode or (nuch better!) uing the [[https://developer.mozilla.org/en-US/docs/Tools][Developer Tools]]in your browser.


