#+DATE: [2010-10-12 Tue 22:23]
#+POSTID: 407
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY:pre-class-notes,  
#+TAGS: abundance, 
#+DESCRIPTION: 
#+TITLE: Notes on Abundance and Classification

I hope by this brief posting to draw some links between the readings for this weeek which at first glance might seem an incoherent assemblage.  The point of this week's class was, for me, to call attention to the problem of abundance which might perhaps have  best been addressed by Roy Rosenzweig's [[http://www.historycooperative.org/journals/ahr/108.3/rosenzweig.html][earlier article]] on the subject.  Rosenzweig, using language that is mirrored in [[http://chnm.gmu.edu/digitalhistory/collecting/][Chapter 6]] of [[http://chnm.gmu.edu/digitalhistory/][Digital History]], draws attention to the extremely difficult problems of information abundance in the era of the web.  There are at least two such problems of tremendous and immediate importance:
1) the difficulty of /locating/ the information you really want in the enormous detritus of the past, and beyond that, of actually /reading/ it;
2) the /extreme transience/ of information and digital formats, such that e.g. extremely important documents can easily disappear without leaving traces of themselves behind, and files can easily become unreadable as the hardware and software required to interpret them becomes obsolete (e.g. the coming obsolescence of Flash -- 50 years from now, who will be able to play Flash 3.0 files?) Consider this example:
#+BEGIN_QUOTE
 But this "system" will not work in the digital era because preservation cannot begin twenty-five years after the fact. What might happen, for example, to the records of a writer active in the 1980s who dies in 2003 after a long illness? Her heirs will find a pile of unreadable 5¼" floppy disks with copies of letters and poems written in WordStar for the CP/M operating system or one of the more than fifty now-forgotten word-processing programs used in the late 1980s. ([[http://www.historycooperative.org/journals/ahr/108.3/rosenzweig.html][Rosenz]]weig)
#+END_QUOTE
These kinds of nightmares are more or less new to our age, and they are challenges we need to confront.  When you build your own websites, you will need to ensure that they are standards-compliant and durable in this sense. /Times/ reporter  Katie Hafner raises similar issues in her article from this week's readings:
#+BEGIN_QUOTE
The ultimate fate of information relating to potentially valuable but obscure people, places, events or things like the Silenus highlights one of the paradoxes of the digital era. While the Internet boom has made information more accessible and widespread than ever, that very ubiquity also threatens records and artifacts that do not easily lend themselves to digitization — because of cost, but also because Web surfers and more devoted data hounds simply find it easier to go online than to travel far and wide to see tangible artifacts.
#+END_QUOTE
If the Internet becomes our only archive, what happens to objects that are not "Internet-able"?  And are there ways to capture artifacts in the information infrastructure of our age?  "Collecting History Online" -- which unlike the Rosenzweig article I quoted above, actually does form part of our readings -- is also concerned with practical questions of how to capture history online in an enduring way.  The prominent example of [[http://911digitalarchive.org/][the September 11 Digital Archive]] itself raises as many questions as it answers, about methods and meanings in particular.  

The readings by Bowker and Star were intended to highlight the ways that information infrastructures arise to deal with problems of abundance, and the ways that those infrastructures shape our experience of the things that they are meant to classify.  The structures of knowledge are a longstanding topic of anthropology; Bowker and Star are interested, though, in the /infrastructures/ of knowledge -- the technical and practical systems that underlie the capacity to know.  They are at pains to show that all historical narratives are constructed around non-obvious classifications -- cf. the discussion on p. 41 of the 'apparently unproblematic statement: " In 1640, the English revolution occurred; this led to a twenty-year period in which the English had no monarchy."'  You should decide for yourselves whether the dependence of this statement on highly contingent notions of time, the classifications of peoples, the classification of events, and the classification of political systems, matters to you; but for thinking about history, it ought to matter that "Whatever appears as universal or indeed standard, is the result of negotiations, organizational processes, and conflict." (p.44) That is, you can expect to find a social and technical apparatus lying behind the most banal truths, /without which those truths lose their validity./ The computational systems that enable our current classificatory systems -- scientific and lay -- affect how and what it is possible to think.  So we can expect that the new forms of historical narrative that we are exploring, alongside Cohen & Rosenzweig and many others, will exert important influences on how we imagine the past. It is not immediately obvious to me, anyway, just what those effects will be, but it's certainly worth thinking about.  
