#+POSTID: 77
#+DATE: [2010-09-21 Tue 07:03]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: 
#+TAGS: publicsphere
#+DESCRIPTION: 

#+TITLE: The WWW as Public Sphere

Just a few quick words about the readings this week, which concern the idea of the  "[[http://en.wikipedia.org/wiki/Public_sphere][Public Sphere]]".  This phrase is rooted in ideas about [[http://plato.stanford.edu/entries/enlightenment/][enlightenment]] that stretch at least back to [[http://en.wikipedia.org/wiki/Immanuel_Kant][Immanuel Kant]].  The analyses of [[http://en.wikipedia.org/wiki/J%C3%BCrgen_Habermas][Jürgen Habermas]] ([[http://plato.stanford.edu/entries/habermas/][SEP entry]]), in particular, developed the idea of a sort of virtual space of critical discussion, in which participants treat each other as equals and are freed from economic or political pressures that might inhibit the authentic exchange of ideas.  While this is in some ways an /ideal/ space, Habermas also contends that it reached a height of development in the real historical circumstances of the Enlightenment, that is, in the decades prior to and just following 1800.  After this period, Habermas argued, the rise of mass media and the pervasive influence of capitalism and its pressures began to undermine this sphere of activity.  

[[http://www.humanities.uci.edu/mposter/][Mark Poster]] was among the first to ask whether the Internet, and in particular the World Wide Web (anyone have a sense of the difference between the two?) provided an opportunity for a resurgence of the Public Sphere.  If the original Public Sphere was largely rooted in one set of social and media technologies (coffee houses, salons), and destroyed by another set of developments (mass media, broadcasting), could this new technology -- not quite so new any more! -- allow it to return to prominence?  This vision has been taken up by a variety of analysts and is still important not only to media studies professors, but to many of the architects of the web itself.  This raises many questions, of course, in particular about the role of technology in these developments (does technology drive the social change all by itself?  or are the effects of a technical innovation shaped by pre-existing social forces and pressures?), and about the definition of "authentic" free discussion (how broadly do we define the topics that are worth discussing?).  There's something of a tension between nostalgia and Utopianism -- that is, between yearning for a bygone era and faithfully believing that an era of perfection is yet to come.  

So, you can bear these issues in mind as you read the texts.  The Habermas text in particular is somewhat more philosophical in its language and style than most of what we'll be reading this term; so don't be too put off by that, but also take time to read it carefully and patiently.  *You /will/ be rewarded for your efforts,* as these are all worth reading.  

In addition to the Poster and Habermas texts, we have two links to the [[http://www.wikileaks.org/][Wikileaks]] scandal from this summer.  The point of those readings is to ask, is this what the Public Sphere looks like?  Your task is not to read the 91000 documents in the [[http://wikileaks.org/wiki/Afghan_War_Diary,_2004-2010][Afghan War Diary]] (though you should certainly watch the [[http://www.wikileaks.org/wiki/Collateral_Murder,_5_Apr_2010][Collateral Murder]] video, which is easiest to do on the [[http://collateralmurder.com/en/index.html][dedicated website]]); instead, you should get a feel for the nature of the documents that have been published here, and for the way that Wikileaks operates; and finally, for the manner in which the scandal proceeded.  So (and this is your lab assignment, basically) you should be tracing the historical development of this phenomenon.  As you do so, think about what tools you use (google?  google news? newspaper indexes? what else?), and tag you bookmarks on delicious with 'hackinghistory' and 'publicsphere', so we can all follow what you're doing.  

See you on Thursday!
Matt
