#+POSTID: 508
#+DATE: [2010-10-21 Thu 10:54]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: 
#+TAGS: crowdsourcing, 
#+DESCRIPTION: 
#+TITLE: Tragedy of the Commons

The term "tragedy of the commons" came up a bunch in class today.  It dates to Garrett Hardin's [[http://www.garretthardinsociety.org/articles/art_tragedy_of_the_commons.html][1968 article of the same name]], in which he uses the destruction of the English common pastures as a sort of metonymy to describe a widespread dynamic in which common ownership of property can lead to a set of incentives that privileges overuse above stewardship of that resource.  Here's how he says it:

#+BEGIN_QUOTE
The tragedy of the commons develops in this way. Picture a pasture open to all. It is to be expected that each herdsman will try to keep as many cattle as possible on the commons. Such an arrangement may work reasonably satisfactorily for centuries because tribal wars, poaching, and disease keep the numbers of both man and beast well below the carrying capacity of the land. Finally, however, comes the day of reckoning, that is, the day when the long-desired goal of social stability becomes a reality. At this point, the inherent logic of the commons remorselessly generates tragedy.

As a rational being, each herdsman seeks to maximize his gain. Explicitly or implicitly, more or less consciously, he asks, "What is the utility to me of adding one more animal to my herd?"...  the rational herdsman concludes that the only sensible course for him to pursue is to add another animal to his herd. And another; and another.... But this is the conclusion reached by each and every rational herdsman sharing a commons. Therein is the tragedy. Each man is locked into a system that compels him to increase his herd without limit--in a world that is limited. Ruin is the destination toward which all men rush, each pursuing his own best interest in a society that believes in the freedom of the commons. Freedom in a commons brings ruin to all. 
#+END_QUOTE

The tragedy of the commons then, is about the conflict between self-interest and communal interest, and the way that commons property can exacerbate that conflict.  Hardin, contrary to many people's first interpretation, recommends /eliminating the commons whenever possible/: 

#+BEGIN_QUOTE
What shall we do? We have several options. We might sell them off as private property. We might keep them as public property, but allocate the right enter them. The allocation might be on the basis of wealth, by the use of an auction system. It might be on the basis merit, as defined by some agreed-upon standards. It might be by lottery. Or it might be on a first-come, first-served basis, administered to long queues. These, I think, are all the reasonable possibilities. They are all objectionable. But we must choose--or acquiesce in the destruction of the commons...
#+END_QUOTE

But an interesting fact about the digital commons: when you use it, it's often not the case that it /gets used up/.  The economy of the copy is different form the economy of the pasture.  So there are lots of reasons to doubt whether the Tragedy of the Commons even applies in this domain -- let alone whether Hardin's solutions to that conundrum are the ones we should implement.  
